CREATE TABLE `teams` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `yearID` smallint NOT NULL,
  `lgID` char(2) DEFAULT NULL,
  `teamID` char(3) NOT NULL,
  `franchID` varchar(3) DEFAULT NULL,
  `divID` char(1) DEFAULT NULL,
  `div_ID` int DEFAULT NULL,
  `teamRank` smallint DEFAULT NULL,
  `G` smallint DEFAULT NULL,
  `Ghome` smallint DEFAULT NULL,
  `W` smallint DEFAULT NULL,
  `L` smallint DEFAULT NULL,
  `DivWin` varchar(1) DEFAULT NULL,
  `WCWin` varchar(1) DEFAULT NULL,
  `LgWin` varchar(1) DEFAULT NULL,
  `WSWin` varchar(1) DEFAULT NULL,
  `R` smallint DEFAULT NULL,
  `AB` smallint DEFAULT NULL,
  `H` smallint DEFAULT NULL,
  `2B` smallint DEFAULT NULL,
  `3B` smallint DEFAULT NULL,
  `HR` smallint DEFAULT NULL,
  `BB` smallint DEFAULT NULL,
  `SO` smallint DEFAULT NULL,
  `SB` smallint DEFAULT NULL,
  `CS` smallint DEFAULT NULL,
  `HBP` smallint DEFAULT NULL,
  `SF` smallint DEFAULT NULL,
  `RA` smallint DEFAULT NULL,
  `ER` smallint DEFAULT NULL,
  `ERA` double DEFAULT NULL,
  `CG` smallint DEFAULT NULL,
  `SHO` smallint DEFAULT NULL,
  `SV` smallint DEFAULT NULL,
  `IPouts` int DEFAULT NULL,
  `HA` smallint DEFAULT NULL,
  `HRA` smallint DEFAULT NULL,
  `BBA` smallint DEFAULT NULL,
  `SOA` smallint DEFAULT NULL,
  `E` int DEFAULT NULL,
  `DP` int DEFAULT NULL,
  `FP` double DEFAULT NULL,
  `name` varchar(50) DEFAULT NULL,
  `park` varchar(255) DEFAULT NULL,
  `attendance` int DEFAULT NULL,
  `BPF` int DEFAULT NULL,
  `PPF` int DEFAULT NULL,
  `teamIDBR` varchar(3) DEFAULT NULL,
  `teamIDlahman45` varchar(3) DEFAULT NULL,
  `teamIDretro` varchar(3) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `yearID` (`yearID`,`lgID`,`teamID`),
  KEY `lgID` (`lgID`),
  CONSTRAINT `teams_ibfk_1` FOREIGN KEY (`lgID`) REFERENCES `leagues` (`lgID`)
) ENGINE=InnoDB AUTO_INCREMENT=2926 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci