DROP TABLE IF EXISTS batting;
CREATE TABLE `batting` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `playerID` varchar(9) NOT NULL,
  `yearID` smallint NOT NULL,
  `stint` smallint NOT NULL,
  `teamID` char(3) DEFAULT NULL,
  `team_ID` int DEFAULT NULL,
  `lgID` char(2) DEFAULT NULL,
  `G` smallint DEFAULT NULL,
  `G_batting` smallint DEFAULT NULL,
  `AB` smallint DEFAULT NULL,
  `R` smallint DEFAULT NULL,
  `H` smallint DEFAULT NULL,
  `2B` smallint DEFAULT NULL,
  `3B` smallint DEFAULT NULL,
  `HR` smallint DEFAULT NULL,
  `RBI` smallint DEFAULT NULL,
  `SB` smallint DEFAULT NULL,
  `CS` smallint DEFAULT NULL,
  `BB` smallint DEFAULT NULL,
  `SO` smallint DEFAULT NULL,
  `IBB` smallint DEFAULT NULL,
  `HBP` smallint DEFAULT NULL,
  `SH` smallint DEFAULT NULL,
  `SF` smallint DEFAULT NULL,
  `GIDP` smallint DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `playerID` (`playerID`,`yearID`,`stint`),
  KEY `lgID` (`lgID`),
  KEY `team_ID` (`team_ID`),
  CONSTRAINT `batting_ibfk_1` FOREIGN KEY (`lgID`) REFERENCES `leagues` (`lgID`),
  CONSTRAINT `batting_ibfk_3` FOREIGN KEY (`playerID`) REFERENCES `people` (`playerID`)
) ENGINE=InnoDB AUTO_INCREMENT=107430 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci