DROP TABLE IF EXISTS appearances;
CREATE TABLE `appearances` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `yearID` smallint NOT NULL,
  `teamID` char(3) NOT NULL,
  `team_ID` int DEFAULT NULL,
  `lgID` char(2) DEFAULT NULL,
  `playerID` varchar(9) NOT NULL,
  `G_all` smallint DEFAULT NULL,
  `GS` smallint DEFAULT NULL,
  `G_batting` smallint DEFAULT NULL,
  `G_defense` smallint DEFAULT NULL,
  `G_p` smallint DEFAULT NULL,
  `G_c` smallint DEFAULT NULL,
  `G_1b` smallint DEFAULT NULL,
  `G_2b` smallint DEFAULT NULL,
  `G_3b` smallint DEFAULT NULL,
  `G_ss` smallint DEFAULT NULL,
  `G_lf` smallint DEFAULT NULL,
  `G_cf` smallint DEFAULT NULL,
  `G_rf` smallint DEFAULT NULL,
  `G_of` smallint DEFAULT NULL,
  `G_dh` smallint DEFAULT NULL,
  `G_ph` smallint DEFAULT NULL,
  `G_pr` smallint DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `yearID` (`yearID`,`teamID`,`playerID`),
  KEY `lgID` (`lgID`),
  KEY `team_ID` (`team_ID`),
  KEY `playerID` (`playerID`),
  CONSTRAINT `appearances_ibfk_1` FOREIGN KEY (`lgID`) REFERENCES `leagues` (`lgID`),
  CONSTRAINT `appearances_ibfk_3` FOREIGN KEY (`playerID`) REFERENCES `people` (`playerID`)
) ENGINE=InnoDB AUTO_INCREMENT=107358 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci