DROP TABLE IF EXISTS pitching;
CREATE TABLE `pitching` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `playerID` varchar(9) NOT NULL,
  `yearID` smallint NOT NULL,
  `stint` smallint NOT NULL,
  `teamID` char(3) DEFAULT NULL,
  `team_ID` int DEFAULT NULL,
  `lgID` char(2) DEFAULT NULL,
  `W` smallint DEFAULT NULL,
  `L` smallint DEFAULT NULL,
  `G` smallint DEFAULT NULL,
  `GS` smallint DEFAULT NULL,
  `CG` smallint DEFAULT NULL,
  `SHO` smallint DEFAULT NULL,
  `SV` smallint DEFAULT NULL,
  `IPouts` int DEFAULT NULL,
  `H` smallint DEFAULT NULL,
  `ER` smallint DEFAULT NULL,
  `HR` smallint DEFAULT NULL,
  `BB` smallint DEFAULT NULL,
  `SO` smallint DEFAULT NULL,
  `BAOpp` double DEFAULT NULL,
  `ERA` double DEFAULT NULL,
  `IBB` smallint DEFAULT NULL,
  `WP` smallint DEFAULT NULL,
  `HBP` smallint DEFAULT NULL,
  `BK` smallint DEFAULT NULL,
  `BFP` smallint DEFAULT NULL,
  `GF` smallint DEFAULT NULL,
  `R` smallint DEFAULT NULL,
  `SH` smallint DEFAULT NULL,
  `SF` smallint DEFAULT NULL,
  `GIDP` smallint DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `playerID` (`playerID`,`yearID`,`stint`),
  KEY `lgID` (`lgID`),
  KEY `team_ID` (`team_ID`),
  CONSTRAINT `pitching_ibfk_1` FOREIGN KEY (`lgID`) REFERENCES `leagues` (`lgID`),
  CONSTRAINT `pitching_ibfk_3` FOREIGN KEY (`playerID`) REFERENCES `people` (`playerID`)
) ENGINE=InnoDB AUTO_INCREMENT=47629 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci